/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jogobandeiras2;

import java.awt.Button;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.SwingConstants;

/**
 *
 * @author jpdia
 */
public class ConteudoPaises extends javax.swing.JFrame {

    /**
     * Creates new form ConteudoPaises
     */
    public ConteudoPaises() {
        initComponents();
        GridLayout gridPaises = new GridLayout(183, 2);
        sPaises = new JScrollPane();
        for(int i =0; i<2;i++){
            try {
                sPaises.add(constroiJPanel(i));
            } catch (URISyntaxException ex) {
                Logger.getLogger(ConteudoPaises.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        this.add(sPaises);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(670, 589));
        setResizable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 589, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
 private final JScrollPane sPaises;

    private JPanel constroiJPanel(int num) throws URISyntaxException, URISyntaxException {
        Sorteio s = new Sorteio(num);
        GridLayout gridDado = new GridLayout(3, 1);
        JPanel painel = new JPanel(gridDado);
        JLabel label = new JLabel();
        label.setIcon(new ImageIcon("resources/Bandeiras/" + s.getPais() + ".png"));
        painel.add(label);
        JLabel labelNome = new JLabel(s.getPais());
        JButton button = ConstroiLink(s.getLink());
        painel.add(labelNome);
        painel.add(button);
        return painel;
    }

    private static void open(URI uri) {
        if (Desktop.isDesktopSupported()) {
            try {
                Desktop.getDesktop().browse(uri);
            } catch (IOException e) {
                /* TODO: error handling */ }
        } else {
            /* TODO: error handling */ }
    }

    private JButton ConstroiLink(String link) throws URISyntaxException {
        final URI uri = new URI(link);
        class OpenUrlAction implements ActionListener {

            @Override
            public void actionPerformed(ActionEvent ae) {
                open(uri);
            }
        }
        JButton button = new JButton();
        button.setText("<HTML>Click the <FONT color=\"#000099\"><U>link</U></FONT>"
                + " to go to the Java website.</HTML>");
        button.setHorizontalAlignment(SwingConstants.LEFT);
        button.setBorderPainted(false);
        button.setOpaque(false);
        button.setBackground(Color.WHITE);
        button.setToolTipText(uri.toString());
        button.addActionListener(new OpenUrlAction());
        return button;
    }

}
